apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nodee 
  janus-idp.io/tekton: nodee
  backstage.io/kubernetes-id: nodee
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nodee
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml