apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nodee
  janus-idp.io/tekton: nodee
  backstage.io/kubernetes-id: nodee
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nodee
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
